In [1]:
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
plt.rcParams['figure.figsize'] = [4, 6]

In [2]:
csv_to_read='portfolio_9_22_2021.csv'
excel_to_read='portfolio_9_22_2021.xlsx'#for currency type and asset class, do not change 
canadianX = 0.79

In [13]:
df =  pd.read_csv(csv_to_read)
xldf = pd.read_excel(excel_to_read)
currency_column = xldf["Trading Currency"]
df['Trading Currency']= currency_column
df.filter(items=['Symbol', 'Position', 'Last','Market Value']).sort_values('Symbol')
currency = []

   Symbol Position    Last Market Value
9     AIG      150   53.88        8,082
11   AMAT       60  138.11        8,288
17    AUY    4,900    4.08       19,968
7      BG      215   77.71       16,707
13    CMI       35  221.99        7,771
8    COPX      170   34.42        5,852
12    EWY      165   82.11       13,549
19    GDX      100   30.51        3,052
1     GLO   12,900   3.200       40,893
20   GOLD      290   18.43        5,345
10     KL      915   42.36       38,759
5     LUN      838   8.970        7,521
2   OGZPY    3,100    9.29       28,815
0    PHOR    1,700   20.72       35,224
4     RIO      150   66.81       10,020
3     RSP      155  151.66       23,507
18    RTI    3,300  C0.065          215
16  SCATC       80  171.10       13,688
14   SILJ      470   12.38        5,814
6     SMH       45  269.93       12,147
21    TMF    3,200   30.42       97,341
15   URNM      300   82.51       24,753
22    VXX      575   27.06       15,560